let all=[];let editing=null;const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,opt={}){const r=await fetch(url,opt);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function check(){try{const x=await api('/api/admin/me');if(x.loggedIn){$('login').hidden=true;$('app').hidden=false;load();}}catch{}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(fd.entries()))});location.reload()}catch(x){alert(x.message)}});
async function load(){all=await api('/api/products');renderProducts();const brands=new Set(all.map(p=>p.brand));$('productCount').textContent=all.length;$('brandCount').textContent=brands.size;try{const o=await api('/api/admin/orders');$('orderCount').textContent=o.length;renderOrders(o)}catch{}}
function renderProducts(){const q=$('filter').value.toLowerCase();const a=all.filter(p=>`${p.brand} ${p.name} ${p.code}`.toLowerCase().includes(q));$('products').innerHTML=a.map(p=>`<div class="product-row"><img src="/${esc(p.image)}"><div><h3>${esc(p.brand)} — ${esc(p.name)}</h3><p>${esc(p.code)} · ${esc(p.category)} · Stock: ${p.stock}</p><p>Original: ${p.original??'-'} | Sale: ${p.sale??'-'}</p></div><div class="actions"><button data-edit="${p.id}">Edit</button><button class="danger" data-delete="${p.id}">Delete</button></div></div>`).join('')||'<p>No products found.</p>'}
function fill(p){editing=p;$('formTitle').textContent='Edit Product';$('saveBtn').textContent='SAVE CHANGES';$('cancelEdit').hidden=false;for(const k of ['brand','name','code','category','original','sale','stock','badge']){const el=document.querySelector(`[name="${k}"]`);if(el)el.value=p[k]??''}window.scrollTo({top:0,behavior:'smooth'})}
$('products').addEventListener('click',async e=>{const ed=e.target.closest('[data-edit]');if(ed){fill(all.find(p=>String(p.id)===ed.dataset.edit));return}const del=e.target.closest('[data-delete]');if(del&&confirm('Delete this product?')){await api('/api/admin/products/'+del.dataset.delete,{method:'DELETE'});load()}});
$('productForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);let url='/api/admin/products',method='POST';if(editing){url+='/'+editing.id;method='PUT'}try{await api(url,{method,body:fd});reset();load();alert('Saved successfully.')}catch(x){alert(x.message)}});
function reset(){$('productForm').reset();document.querySelector('[name="stock"]').value=10;editing=null;$('formTitle').textContent='Add Product';$('saveBtn').textContent='ADD PRODUCT';$('cancelEdit').hidden=true}
$('cancelEdit').addEventListener('click',reset);$('filter').addEventListener('input',renderProducts);$('logout').addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()});$('refreshOrders').addEventListener('click',async()=>renderOrders(await api('/api/admin/orders')));
function renderOrders(o){$('orders').innerHTML=o.length?o.map(x=>`<div class="order"><h3>${esc(x.id)} <small>${esc(x.status)}</small></h3><p>${esc(x.customer?.name)} · ${esc(x.customer?.phone)} · ${esc(x.customer?.city)}</p><p>${esc(x.customer?.address)}</p><p><b>${esc(x.total)}</b> · ${esc(x.customer?.payment)}</p><pre>${esc(JSON.stringify(x.items,null,2))}</pre></div>`).join(''):'<p>No orders yet.</p>'}
check();
